from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
# Import your working LangGraph AI brain
from graph.workflow import app as langgraph_app

# 1. This is like your Django project setup
app = FastAPI()
@app.get("/")
@app.post("/")
async def root_endpoint():
    print("⚠️ Something just hit the root endpoint!")
    return {"message": "Climate Risk API is Live! Please send requests to /api/analyze-risk"}
# 2. This is like django-cors-headers. It allows your React frontend to talk to this backend.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], 
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class RiskRequest(BaseModel):
    city: str
    profession: str
    concern: str

class AlertRequest(BaseModel):
    dispatch_text: str
    logistics: dict
    recipient_email: str
    
@app.post("/api/analyze-risk")
async def analyze_risk(request: RiskRequest):
    print(f"📥 Received request from React: {request.city}, {request.concern}")
    
    initial_state = {
        "city": request.city,
        "profession": request.profession,
        "concern": request.concern,
        "city_baseline": {},
        "live_weather": {},
        "historical_weather": [],
        "forecast_weather": [],
        "risk_assessments": {},
        "overall_severity": "Low",
        "general_recommendations": [],
        "personalized_recommendations": [],
        "safe_cities": []
    }
    
    final_state = langgraph_app.invoke(initial_state)
    
    # Return the data to React (FastAPI handles the JSON conversion automatically, just like JsonResponse in Django)
    return final_state

@app.post("/api/send-alert")
async def send_alert(request: AlertRequest):
    print(f"📧 Preparing to send alert to: {request.recipient_email}")
    
    # Format the email body beautifully
    email_body = f"""
    *** OFFICIAL PDMA AUTOMATED SITREP ***
    
    {request.dispatch_text}
    
    *** LOGISTICAL REQUIREMENTS ***
    Water Needed: {request.logistics.get('water_liters', 0)} Liters
    Tents Needed: {request.logistics.get('tents', 0)}
    Medical Kits: {request.logistics.get('medical_kits', 0)}
    
    Generated by Climate Risk AI Agent.
    """
    
    # --- REAL EMAIL SETUP (Optional) ---
    # If you want this to actually send an email, put your Gmail and an "App Password" here.
    # Note: You cannot use your normal Gmail password, you must generate an App Password in your Google Account settings.
    SENDER_EMAIL = "alihaiderno09@gmail.com" 
    SENDER_PASSWORD = "dkgl pzsu kpvk frxm" 
    
    # Switch this to True if you put your real email/password above!
    USE_REAL_EMAIL = True
    
    if USE_REAL_EMAIL:
        try:
            msg = MIMEMultipart()
            msg['From'] = SENDER_EMAIL
            msg['To'] = request.recipient_email
            msg['Subject'] = "URGENT: Climate Disaster SitRep & Logistics Required"
            msg.attach(MIMEText(email_body, 'plain'))
            
            # Connect to Gmail Server
            server = smtplib.SMTP('smtp.gmail.com', 587)
            server.starttls()
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            server.send_message(msg)
            server.quit()
            
            print(" Real email successfully sent!")
            return {"status": "success", "message": f"Alert successfully emailed to {request.recipient_email}."}
        except Exception as e:
            print(f"❌Failed to send email: {e}")
            return {"status": "error", "message": str(e)}
            
    else:
    
        print("\n" + "="*50)
        print(f"🚀 [MOCK MODE] EMAIL SENT TO: {request.recipient_email}")
        print("SUBJECT: URGENT: Climate Disaster SitRep & Logistics Required")
        print(email_body)
        print("="*50 + "\n")
        
        return {"status": "success", "message": f"[DEMO] Alert successfully emailed to {request.recipient_email}."}
    
if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)